/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Modelo.Funcion;
import Modelo.Lugar;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCO
 */
public final class DialogLugaresDisponibles extends javax.swing.JDialog {

    private final LugarData lugarData;
    private final Funcion funcion;
    private final FuncionData funcionData;
    private final List<Lugar> lugaresReservados;

    public DialogLugaresDisponibles(java.awt.Frame parent, boolean modal, LugarData lugarData, FuncionData funcionData, Funcion funcion) {
        super(parent, modal);
        this.lugarData = lugarData;
        this.funcionData = funcionData;
        this.funcion = funcion;
        lugaresReservados = new ArrayList<>();
        initComponents();
        cargarLugares();
    }

    public void cargarLugares() {
        lugarData.setFuncionData(funcionData);
        funcion.setLugaresDisponibles(lugarData.obtenerLugaresDisponiblesPorFuncion(funcion.getCodFuncion()));
        DefaultTableModel modelo = (DefaultTableModel) tablaLugares.getModel();
        modelo.setRowCount(0);

        for (Lugar l : funcion.getLugaresDisponibles()) {
            Object[] fila = {l.getCodLugar(),
                l.getFila(),
                l.getNumero(),
                l.isEstado() ? "Ocupado" : "Disponible",
                l.getFuncion().getCodFuncion()};
            modelo.addRow(fila);
        }
    }
    
    public void agregarLugar(Lugar nuevoLugar) {
    boolean existe = false;

    for (Lugar l : lugaresReservados) {
        if (l.getCodLugar() == nuevoLugar.getCodLugar()) {
            existe = true;
            break;
        }
    }

    if (!existe) {
        lugaresReservados.add(nuevoLugar);
         JOptionPane.showMessageDialog(this, "Lugar Reservado correctamente en la lista.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
      JOptionPane.showMessageDialog(this, "el lugar ya esta reservado en la lista", "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        butCancelar = new javax.swing.JButton();
        butReservarAsientos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLugares = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservar Lugares");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\icons8-cross-mark-48.png")); // NOI18N
        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 230, 70));

        butReservarAsientos.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\asiento-de-cine.png")); // NOI18N
        butReservarAsientos.setText("Reservar Asiento/s");
        butReservarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReservarAsientosActionPerformed(evt);
            }
        });
        getContentPane().add(butReservarAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 230, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reserva de Lugares");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        tablaLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodLugar", "Fila", "Numero", "Estado", "CodFuncion"
            }
        ));
        tablaLugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLugaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaLugares);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\fondo.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        if(lugaresReservados.isEmpty()){
             JOptionPane.showMessageDialog(this, "No hay lugares reservados en la lista", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        lugaresReservados.clear();
         JOptionPane.showMessageDialog(this, "Se quitaron los lugares reservados de la lista.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butReservarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReservarAsientosActionPerformed
        
         if (tablaLugares.isEditing()) {
            tablaLugares.getCellEditor().stopCellEditing();
        }
        int filaSeleccionada = tablaLugares.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila.");
            return;
        }

        int filaModelo = tablaLugares.convertRowIndexToModel(filaSeleccionada);

        String codLugar = tablaLugares.getModel().getValueAt(filaModelo, 0).toString();
        String fila = tablaLugares.getModel().getValueAt(filaModelo, 1).toString();
        String numero = tablaLugares.getModel().getValueAt(filaModelo, 2).toString();
        String estadoStr = tablaLugares.getModel().getValueAt(filaModelo, 3).toString();

        int codLugarInt = Integer.parseInt(codLugar);
        char filaLetra = fila.charAt(0);
        int numeroAsiento = Integer.parseInt(numero);

        boolean estado = false;
        if (estadoStr.equals("Ocupado")) {
            estado = true;
        }
        
      
        Lugar lugar = new Lugar(codLugarInt, filaLetra, numeroAsiento, estado, funcion);
        
          
          agregarLugar(lugar);
       
        cargarLugares();
    }//GEN-LAST:event_butReservarAsientosActionPerformed

    private void tablaLugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLugaresMouseClicked
       
    }//GEN-LAST:event_tablaLugaresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butReservarAsientos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaLugares;
    // End of variables declaration//GEN-END:variables

    List<Lugar> getLugaresReservados() {
        return lugaresReservados;
    }
}
