/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Funcion;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCO
 */
public class NuevoLugar extends javax.swing.JInternalFrame {

    private final LugarData lugarData;
    private final FuncionData funcionData;

    public NuevoLugar(LugarData lugarData, FuncionData funcionData) {
        this.lugarData = lugarData;
        this.funcionData = funcionData;
        initComponents();
        cargarFunciones();
    }
    
    private void limpiarCampos() {
    boxFunciones.setSelectedIndex(0); 
    txtCantidad.setText("");            
    txtCapacidad.setText("");         
}


    private void cargarFunciones() {
        boxFunciones.removeAllItems();
        try {
            List<Funcion> lista = funcionData.listarFunciones();
            for (Funcion f : lista) {

                boxFunciones.addItem(f.getCodFuncion() + " " + " - " + f.getPelicula().getTitulo() + " " + " - " + f.getSalaFuncion().getNroSala() + " " + " - " + f.getHoraInicio());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las funciones: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFuncion = new javax.swing.JLabel();
        boxFunciones = new javax.swing.JComboBox<>();
        butAgregar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidad = new java.awt.TextField();
        ImageIcon icono = new ImageIcon(getClass().getResource("/Fondos/img/fondo-administracion2.jpg"));
        Image miImagen = icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0, getWidth(), getHeight(),this);
            }

        };
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFuncion.setForeground(new java.awt.Color(255, 255, 255));
        labelFuncion.setText("Funcion:");
        getContentPane().add(labelFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        boxFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFuncionesActionPerformed(evt);
            }
        });
        boxFunciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                boxFuncionesKeyReleased(evt);
            }
        });
        getContentPane().add(boxFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 250, -1));

        butAgregar.setText("Agregar");
        butAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(butAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 97, 45));

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        butCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butCancelarKeyReleased(evt);
            }
        });
        getContentPane().add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 90, 45));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 149, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 145, 113, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacidad (Sala)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 246, -1, -1));

        txtCapacidad.setEditable(false);
        txtCapacidad.setEnabled(false);
        getContentPane().add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 246, 120, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevos Lugares");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarActionPerformed
        if (boxFunciones.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una función.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String funcionSeleccionada = boxFunciones.getSelectedItem().toString();
        String[] partes = funcionSeleccionada.split(" - ");
        int codFuncion = Integer.parseInt(partes[0].trim());

        int cantidad = Integer.parseInt(txtCantidad.getText().trim());

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        lugarData.crearLugaresParaFuncion(codFuncion, cantidad);

        JOptionPane.showMessageDialog(this, "Lugares creados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Verifique que la cantidad sea un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al crear lugares: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } catch (RuntimeException ex) {
        JOptionPane.showMessageDialog(this, "Error de validación: " + ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_butAgregarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        txtCantidad.setText("");
        boxFunciones.setSelectedIndex(0);
        txtCapacidad.setText("");
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butCancelarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancelarKeyReleased

    private void boxFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFuncionesActionPerformed
        String funcionSeleccionado = boxFunciones.getSelectedItem().toString();
        String[] partes = funcionSeleccionado.split(" - ");
        String txtCodFuncion = partes[0].trim();
        int codFuncion = Integer.parseInt(txtCodFuncion);
        
        try {
            int capacidad = funcionData.buscarFuncion(codFuncion).getSalaFuncion().getCapacidad();
            txtCapacidad.setText(String.valueOf(capacidad));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener la capacidad: " + ex.getMessage());
        }
    }//GEN-LAST:event_boxFuncionesActionPerformed

    private void boxFuncionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxFuncionesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFuncionesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFunciones;
    private javax.swing.JButton butAgregar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelFuncion;
    private java.awt.TextField txtCantidad;
    private java.awt.TextField txtCapacidad;
    // End of variables declaration//GEN-END:variables
}
