/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;


import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Sala;
import Persistencia.FuncionData;
import Persistencia.PeliculaData;
import Persistencia.SalaData;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Emiliano
 */
public class NuevaFuncion extends javax.swing.JInternalFrame {
    
    private PeliculaData pData = new PeliculaData();
    private SalaData sData = new SalaData();
    private FuncionData fData = new FuncionData();
    /**
     * Creates new form NuevaFuncion
     */
    public NuevaFuncion() {
        initComponents();
        pData = new PeliculaData();
        sData = new SalaData();
        fData = new FuncionData();
        cargarPeliculas();
        cargarSalas();
        cargarIdiomas();


    }
    private void cargarPeliculas(){
        try{
            List<Pelicula> lista = pData.listarPeliculas();
            CBoxPeliculas.removeAllItems();
            for(Pelicula p : lista){
                CBoxPeliculas.addItem(p);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al cargar peliculas: "+ e.getMessage());
        }
    }
    private void cargarSalas(){
        try{
            List<Sala> lista = sData.listarSalas();
            CBoxSalas.removeAllItems();
            for (Sala s : lista){
                CBoxSalas.addItem(s);
            }
        } catch ( Exception e){
            JOptionPane.showMessageDialog(this, "Error al cargar salas: "+ e.getMessage());
        }
    }
    private void cargarIdiomas(){
        CBoxIdiomas.removeAllItems();
        CBoxIdiomas.addItem("Español");
        CBoxIdiomas.addItem("Ingles");
        CBoxIdiomas.addItem("Frances");
        CBoxIdiomas.addItem("Portugues");
                
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        JLPelicula = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CBoxPeliculas = new javax.swing.JComboBox();
        JLSala = new javax.swing.JLabel();
        CBoxSalas = new javax.swing.JComboBox();
        JLIdioma = new javax.swing.JLabel();
        CBoxIdiomas = new javax.swing.JComboBox();
        JLFecha = new javax.swing.JLabel();
        DChooserFecha = new com.toedter.calendar.JDateChooser();
        JLInicio = new javax.swing.JLabel();
        TexHoraInicio = new javax.swing.JTextField();
        JLFin = new javax.swing.JLabel();
        TexHoraFin = new javax.swing.JTextField();
        JLPrecio = new javax.swing.JLabel();
        TexPrecio = new javax.swing.JTextField();
        CBox3D = new javax.swing.JCheckBox();
        CBoxSubtitulo = new javax.swing.JCheckBox();
        JlOpciones = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ButGuardar = new javax.swing.JButton();
        ButLimpiar = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setTitle("Nuevas Funciones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        Titulo.setText("Nueva Funcion");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        JLPelicula.setText("Pelicula :");
        getContentPane().add(JLPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 10));

        getContentPane().add(CBoxPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, -1));

        JLSala.setText("Sala :");
        getContentPane().add(JLSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, 20));

        getContentPane().add(CBoxSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 130, -1));

        JLIdioma.setText("Idioma :");
        getContentPane().add(JLIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        getContentPane().add(CBoxIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));

        JLFecha.setText("Fecha Funcion :");
        getContentPane().add(JLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 20));
        getContentPane().add(DChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 130, -1));

        JLInicio.setText("Hora Inicio :");
        getContentPane().add(JLInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 20));
        getContentPane().add(TexHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        JLFin.setText("Hora Fin");
        getContentPane().add(JLFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));
        getContentPane().add(TexHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));

        JLPrecio.setText("Precio Lugar :");
        getContentPane().add(JLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 20));

        TexPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(TexPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, -1));

        CBox3D.setText("3D");
        CBox3D.setToolTipText("");
        CBox3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox3DActionPerformed(evt);
            }
        });
        getContentPane().add(CBox3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 50, -1));

        CBoxSubtitulo.setText("Subtitulada");
        getContentPane().add(CBoxSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        JlOpciones.setText("Opciones :");
        getContentPane().add(JlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 60, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 410, 10));

        ButGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Iconos/ahorrar.png"))); // NOI18N
        ButGuardar.setText("Guardar");
        ButGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(ButGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        ButLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Iconos/escoba.png"))); // NOI18N
        ButLimpiar.setText("Limpiar");
        ButLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(ButLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        ButCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Iconos/cerrar.png"))); // NOI18N
        ButCancelar.setText("Cerrar");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(ButCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TexPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexPrecioActionPerformed

    private void CBox3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox3DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBox3DActionPerformed

    private void ButLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimpiarActionPerformed
        // TODO add your handling code here:
    CBoxPeliculas.setSelectedIndex(0);
    CBoxSalas.setSelectedIndex(0);
    CBoxIdiomas.setSelectedIndex(0);
    DChooserFecha.setDate(null);
    TexHoraInicio.setText("");
    TexHoraFin.setText("");
    TexPrecio.setText("");
    CBox3D.setSelected(false);
    CBoxSubtitulo.setSelected(false);
    }//GEN-LAST:event_ButLimpiarActionPerformed

    private void ButGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButGuardarActionPerformed

      try {
        
        String pPeli = (String) CBoxPeliculas.getSelectedItem();
        if (pPeli == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una pelicula.");
            return;
        }
        int codPelicula = Integer.parseInt(pPeli.split(" - ")[0]);

        
        String sSala = (String) CBoxSalas.getSelectedItem();
        if (sSala == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una sala.");
            return;
        }
        int nroSala = Integer.parseInt(sSala);

       
        String idioma = (String) CBoxIdiomas.getSelectedItem();

       
        Date fechaDate = DChooserFecha.getDate();
        if (fechaDate == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la fecha de funcion.");
            return;
        }
        LocalDate fechaFuncion = fechaDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        
        String horaInicioStr = TexHoraInicio.getText();
        String horaFinStr = TexHoraFin.getText();

        if (horaInicioStr.isEmpty() || horaFinStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar las horas.");
            return;
        }

        LocalTime horaInicio = LocalTime.parse(horaInicioStr);
        LocalTime horaFin = LocalTime.parse(horaFinStr);

        if (horaFin.isBefore(horaInicio)) {
            JOptionPane.showMessageDialog(this, "La hora de fin no puede ser antes que la de inicio.");
            return;
        }

        
        double precio = Double.parseDouble(TexPrecio.getText());

        
        boolean es3D = CBox3D.isSelected();
        boolean subtitulada = CBoxSubtitulo.isSelected();

        
        Pelicula peli = pData.buscarPelicula(codPelicula);
        Sala sala = sData.buscarSalaPorNro(nroSala);

        Funcion f = new Funcion();
        f.setPelicula(peli);
        f.setSalaFuncion(sala);
        f.setIdioma(idioma);
        f.setFecha(fechaFuncion);
        f.setHoraInicio(horaInicio);
        f.setHoraFin(horaFin);
        f.setPrecioLugar(precio);
        f.setEs3d(es3D);
        f.setSubtitulada(subtitulada);
        f.setEstado(true);

        boolean exito = fData.insertarFuncion(f);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Funcion creada con exito.");

        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la funcion.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_ButGuardarActionPerformed

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButGuardar;
    private javax.swing.JButton ButLimpiar;
    private javax.swing.JCheckBox CBox3D;
    private javax.swing.JComboBox CBoxIdiomas;
    private javax.swing.JComboBox CBoxPeliculas;
    private javax.swing.JComboBox CBoxSalas;
    private javax.swing.JCheckBox CBoxSubtitulo;
    private com.toedter.calendar.JDateChooser DChooserFecha;
    private javax.swing.JLabel JLFecha;
    private javax.swing.JLabel JLFin;
    private javax.swing.JLabel JLIdioma;
    private javax.swing.JLabel JLInicio;
    private javax.swing.JLabel JLPelicula;
    private javax.swing.JLabel JLPrecio;
    private javax.swing.JLabel JLSala;
    private javax.swing.JLabel JlOpciones;
    private javax.swing.JTextField TexHoraFin;
    private javax.swing.JTextField TexHoraInicio;
    private javax.swing.JTextField TexPrecio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
