/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Comprador;
import Persistencia.CompradorData;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCO
 */
public class NuevoComprador extends javax.swing.JInternalFrame {

    CompradorData compradorData;

    public NuevoComprador(CompradorData compradorData) {
        this.compradorData = compradorData;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtActores = new javax.swing.JTextField();
        butAgregar = new javax.swing.JButton();
        txtOrigen = new javax.swing.JTextField();
        butCancelar = new javax.swing.JButton();
        txtGenero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbutEnCartelera = new javax.swing.JToggleButton();
        dateEstreno = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        tbutEstado = new javax.swing.JToggleButton();
        dateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ImageIcon icono = new ImageIcon(getClass().getResource("/Fondos/img/fondo-administracion2.jpg")); Image miImagen = icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0, getWidth(), getHeight(),this);
            }

        };
        butAgregar1 = new javax.swing.JButton();
        butCancelar1 = new javax.swing.JButton();

        jLabel3.setText("(Por defecto es NO)");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorActionPerformed(evt);
            }
        });

        txtActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActoresActionPerformed(evt);
            }
        });

        butAgregar.setText("Agregar");
        butAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarActionPerformed(evt);
            }
        });

        txtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenActionPerformed(evt);
            }
        });

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        butCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butCancelarKeyReleased(evt);
            }
        });

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        jLabel1.setText("En Cartelera:");

        tbutEnCartelera.setText("Si/No");
        tbutEnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbutEnCarteleraActionPerformed(evt);
            }
        });

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Comprador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 6, -1, 41));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(Por defecto es NO)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 255, -1, -1));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 94, 276, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 134, 276, -1));

        tbutEstado.setText("Si/No");
        tbutEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbutEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(tbutEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 252, -1, -1));
        getContentPane().add(dateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 174, 100, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 97, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 137, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de nacimiento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 174, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 215, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 212, 276, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 255, -1, -1));

        butAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/agregar-usuario.png"))); // NOI18N
        butAgregar1.setText("Agregar");
        butAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(butAgregar1);
        butAgregar1.setBounds(130, 310, 130, 45);

        butCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/icons8-cross-mark-48.png"))); // NOI18N
        butCancelar1.setText("Cancelar");
        butCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelar1ActionPerformed(evt);
            }
        });
        butCancelar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butCancelar1KeyReleased(evt);
            }
        });
        jDesktopPane1.add(butCancelar1);
        butCancelar1.setBounds(290, 310, 130, 45);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarCampos() {
        Date date = null;
        dateFechaNacimiento.setDate(date);
        txtNombre.setText("");
        txtDni.setText("");
        txtTitulo.setText("");
        txtPassword.setText("");
    }
    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorActionPerformed

    private void txtActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActoresActionPerformed

    private void butAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarActionPerformed


    }//GEN-LAST:event_butAgregarActionPerformed

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed

        limpiarCampos();
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butCancelarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancelarKeyReleased

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void tbutEnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbutEnCarteleraActionPerformed

    }//GEN-LAST:event_tbutEnCarteleraActionPerformed

    private void butAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregar1ActionPerformed
        String txtdni = txtDni.getText();
        String txtnombre = txtNombre.getText();
        String txtpassword = txtPassword.getText();
        boolean txtEstado = false;
        if (tbutEstado.isSelected()) {
            txtEstado = true;
        }

        Date dateFechaNac = dateFechaNacimiento.getDate();

        if (txtdni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un dni", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtnombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtpassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (dateEstreno == null) {
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de nacimiento", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Conversion+
        int dni = Integer.parseInt(txtdni);
        LocalDate fechaNacimiento = dateFechaNac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Comprador comprador = new Comprador(-1, dni, txtnombre, fechaNacimiento, txtpassword, txtEstado);

        // --- 3. MANEJO DE ERRORES DE LÓGICA Y BASE DE DATOS ---
        try {

            if (compradorData.insertarComprador(comprador)) {
                JOptionPane.showMessageDialog(this, "Comprador guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                limpiarCampos();

            } else {
                JOptionPane.showMessageDialog(this, "El comprador no se pudo guardar (filas no afectadas).", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IllegalArgumentException ex) {

            JOptionPane.showMessageDialog(this, "Error de validación: " + ex.getMessage(), "Datos Incorrectos", JOptionPane.WARNING_MESSAGE);

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butAgregar1ActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void butCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelar1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_butCancelar1ActionPerformed

    private void butCancelar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butCancelar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancelar1KeyReleased

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void tbutEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbutEstadoActionPerformed

    }//GEN-LAST:event_tbutEstadoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAgregar;
    private javax.swing.JButton butAgregar1;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butCancelar1;
    private com.toedter.calendar.JDateChooser dateEstreno;
    private com.toedter.calendar.JDateChooser dateFechaNacimiento;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton tbutEnCartelera;
    private javax.swing.JToggleButton tbutEstado;
    private javax.swing.JTextField txtActores;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
