/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Emiliano
 */
public class NuevaFuncion extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaFuncion
     */
    public NuevaFuncion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLPelicula = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BoxPeliculas = new javax.swing.JComboBox<>();
        JLSala = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        JLFecha = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        JLInicio = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JLFin = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        JLPrecio = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        JLOpciones = new javax.swing.JLabel();
        CBox3D = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        jLabel1.setText("Nueva Funcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        JLPelicula.setText("Pelicula :");
        getContentPane().add(JLPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 10));

        getContentPane().add(BoxPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 130, -1));

        JLSala.setText("Sala :");
        getContentPane().add(JLSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 40, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, -1));

        jLabel3.setText("Idioma :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, -1));

        JLFecha.setText("Fecha Funcion :");
        getContentPane().add(JLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, -1));

        JLInicio.setText("Hora Inicio :");
        getContentPane().add(JLInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, -1));

        JLFin.setText("Hora Fin");
        getContentPane().add(JLFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, -1));

        JLPrecio.setText("Precio Lugar :");
        getContentPane().add(JLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 20));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 90, -1));

        JLOpciones.setText("Opciones :");
        getContentPane().add(JLOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, 20));

        CBox3D.setText("3D");
        getContentPane().add(CBox3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jCheckBox2.setText("Subtitulada");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxPeliculas;
    private javax.swing.JCheckBox CBox3D;
    private javax.swing.JLabel JLFecha;
    private javax.swing.JLabel JLFin;
    private javax.swing.JLabel JLInicio;
    private javax.swing.JLabel JLOpciones;
    private javax.swing.JLabel JLPelicula;
    private javax.swing.JLabel JLPrecio;
    private javax.swing.JLabel JLSala;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
