/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Funcion;
import Modelo.Lugar;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCO
 */
public class NuevoLugar extends javax.swing.JInternalFrame {

    private LugarData lugarData;
    private FuncionData funcionData;

    public NuevoLugar(LugarData lugarData, FuncionData funcionData) {
        this.lugarData = lugarData;
        this.funcionData = funcionData;
        initComponents();
        cargarFunciones();
    }

    private void cargarFunciones() {
        boxFunciones.removeAllItems();
        try {
            List<Funcion> lista = funcionData.listarFunciones();
            for (Funcion f : lista) {

                boxFunciones.addItem(f.getCodFuncion() + " " + " - " + f.getPelicula().getTitulo() + " " + " - " + f.getSalaFuncion().getNroSala() + " " + " - " + f.getHoraInicio());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las funciones: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelFuncion = new javax.swing.JLabel();
        boxFunciones = new javax.swing.JComboBox<>();
        butAgregar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidad = new java.awt.TextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nuevos Lugares");

        labelFuncion.setText("Funcion:");

        boxFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFuncionesActionPerformed(evt);
            }
        });
        boxFunciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                boxFuncionesKeyReleased(evt);
            }
        });

        butAgregar.setText("Agregar");
        butAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarActionPerformed(evt);
            }
        });

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        butCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butCancelarKeyReleased(evt);
            }
        });

        jLabel2.setText("Cantidad:");

        jLabel3.setText("Capacidad (Sala)");

        txtCapacidad.setEditable(false);
        txtCapacidad.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(butAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(labelFuncion)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFuncion))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarActionPerformed
       String funcionSeleccionado = boxFunciones.getSelectedItem().toString();
        String[] partes = funcionSeleccionado.split(" - ");
        String txtCodFuncion = partes[0].trim();
        int codFuncion = Integer.parseInt(txtCodFuncion);
        String txtcantidad = txtCantidad.getText();
       int cantidad = Integer.parseInt(txtcantidad);
       String txtcapacidad = txtCapacidad.getText();
       int capacidad = Integer.parseInt(txtcapacidad);
       boolean bandera=true;
       if(cantidad>capacidad){
           JOptionPane.showMessageDialog(this, "Error! La cantidad de asientos debe ser menor a la capacidad: ");
           bandera=false;
           return;
       }
       
        try {
            List<Lugar> lugares = lugarData.obtenerLugaresPorFuncion(codFuncion);
            
            if(lugares.size()==capacidad){
              JOptionPane.showMessageDialog(this, "Error! La funcion ya tiene todo los lugares");
              bandera=false;
            }
            lugarData.crearLugaresParaFuncion(codFuncion,cantidad);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, "Error al crear lugares para la funcion: " + ex.getMessage());
             bandera=false;
             return;
        }
        
        if(bandera==true){
        JOptionPane.showMessageDialog(null, "Se crearon lugares correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_butAgregarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        txtCantidad.setText("");
        boxFunciones.setSelectedIndex(0);
        txtCapacidad.setText("");
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butCancelarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancelarKeyReleased

    private void boxFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFuncionesActionPerformed
        String funcionSeleccionado = boxFunciones.getSelectedItem().toString();
        String[] partes = funcionSeleccionado.split(" - ");
        String txtCodFuncion = partes[0].trim();
        int codFuncion = Integer.parseInt(txtCodFuncion);
        
        try {
            int capacidad = funcionData.buscarFuncion(codFuncion).getSalaFuncion().getCapacidad();
            txtCapacidad.setText(String.valueOf(capacidad));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener la capacidad: " + ex.getMessage());
        }
    }//GEN-LAST:event_boxFuncionesActionPerformed

    private void boxFuncionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxFuncionesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFuncionesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFunciones;
    private javax.swing.JButton butAgregar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelFuncion;
    private java.awt.TextField txtCantidad;
    private java.awt.TextField txtCapacidad;
    // End of variables declaration//GEN-END:variables
}
