/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCO
 */
public class VistaPelicula extends javax.swing.JInternalFrame {

    private final PeliculaData peliculaData;

    public VistaPelicula(PeliculaData peliculaData) {
        initComponents();
        
        this.peliculaData = peliculaData;
        
        
        cargarPeliculas();
    }

    private void cargarPeliculas() {
        List<Pelicula> listaPeliculas = null;
        try {
            listaPeliculas = peliculaData.listarPeliculas();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las películas de la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaPeliculas.getModel();
        modelo.setRowCount(0);

        if (listaPeliculas == null) {
            JOptionPane.showMessageDialog(this,
                    "Error, no hay peliculas cargadas en la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Pelicula pelicula : listaPeliculas) {
            Object[] fila = {pelicula.getCodPelicula(), pelicula.getTitulo(), pelicula.getDirector(), pelicula.getActores(), pelicula.getOrigen(), pelicula.getGenero(), pelicula.getEstreno(), pelicula.isEnCartelera()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        PeliculaDesktop = new javax.swing.JDesktopPane();
        butCancelar = new javax.swing.JButton();
        butNuevaPelicula = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPeliculas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarPelicula = new java.awt.TextField();
        butBuscar = new javax.swing.JButton();
        butBuscarPorCartelera = new javax.swing.JButton();
        butGuardarCambios = new javax.swing.JButton();
        butReiniciarTabla = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);

        PeliculaDesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 544, 112, 50));

        butNuevaPelicula.setText("Nueva Pelicula");
        butNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevaPeliculaActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butNuevaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 544, 135, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Pelicula");
        PeliculaDesktop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 6, -1, -1));
        PeliculaDesktop.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 320, -1, -1));

        TablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CodPelicula", "titulo", "director", "actores", "origen", "genero", "estreno", "enCartelera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPeliculas);

        PeliculaDesktop.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 99, 747, -1));

        jLabel2.setText("Buscar Pelicula:");
        PeliculaDesktop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 69, -1, -1));
        PeliculaDesktop.add(txtBuscarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 69, 170, -1));

        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 62, -1, -1));

        butBuscarPorCartelera.setText("Buscar Por Cartelera");
        butBuscarPorCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarPorCarteleraActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butBuscarPorCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 62, -1, -1));

        butGuardarCambios.setText("Guardar Cambios");
        butGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarCambiosActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 544, 145, 50));

        butReiniciarTabla.setText("Reiniciar Tabla");
        butReiniciarTabla.setPreferredSize(new java.awt.Dimension(300, 199));
        butReiniciarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReiniciarTablaActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butReiniciarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 544, 132, 50));

        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        PeliculaDesktop.add(butEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 544, 117, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PeliculaDesktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PeliculaDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNuevaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevaPeliculaActionPerformed

        NuevaPelicula vp = new NuevaPelicula(peliculaData);
        PeliculaDesktop.add(vp);
        vp.setVisible(true);
    }//GEN-LAST:event_butNuevaPeliculaActionPerformed

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        String buscarPelicula = txtBuscarPelicula.getText();
        int codPelicula = 0;

        if (buscarPelicula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo de la pelicula", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            codPelicula = Integer.parseInt(buscarPelicula);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Pelicula pelicula = null;
        try {
            pelicula = peliculaData.buscarPelicula(codPelicula);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (pelicula == null) {
            JOptionPane.showMessageDialog(this, "No se encontro la pelicula con ese id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaPeliculas.getModel();
        modelo.setRowCount(0);
        Object[] fila = {pelicula.getCodPelicula(), pelicula.getTitulo(), pelicula.getDirector(), pelicula.getActores(), pelicula.getOrigen(), pelicula.getGenero(), pelicula.getEstreno(), pelicula.isEnCartelera()};
        modelo.addRow(fila);
    }//GEN-LAST:event_butBuscarActionPerformed

    private void butGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarCambiosActionPerformed

        if (TablaPeliculas.isEditing()) {
            TablaPeliculas.getCellEditor().stopCellEditing();
        }

        int filaSeleccionada = TablaPeliculas.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para modificar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            int codPelicula = Integer.parseInt(TablaPeliculas.getValueAt(filaSeleccionada, 0).toString());
            String titulo = TablaPeliculas.getValueAt(filaSeleccionada, 1).toString();
            String director = TablaPeliculas.getValueAt(filaSeleccionada, 2).toString();
            String actores = TablaPeliculas.getValueAt(filaSeleccionada, 3).toString();
            String origen = TablaPeliculas.getValueAt(filaSeleccionada, 4).toString();
            String genero = TablaPeliculas.getValueAt(filaSeleccionada, 5).toString();

            LocalDate estreno = LocalDate.parse(TablaPeliculas.getValueAt(filaSeleccionada, 6).toString());

            boolean enCartelera = Boolean.parseBoolean(TablaPeliculas.getValueAt(filaSeleccionada, 7).toString());

            Pelicula peliculaModificada = new Pelicula(codPelicula, titulo, director, actores, origen, genero, estreno, enCartelera);

            boolean exito = peliculaData.actualizarPelicula(peliculaModificada);

            if (exito) {
                JOptionPane.showMessageDialog(this, "¡La pelicula se modifico correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                cargarPeliculas();

            } else {

                JOptionPane.showMessageDialog(this,
                        "La película no se pudo actualizar (0 filas afectadas).",
                        "Error de Actualización",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            // Error si el ID o algún número de la tabla no es válido
            JOptionPane.showMessageDialog(this, "Error en el formato de los datos de la tabla.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (java.time.format.DateTimeParseException e) {
            // Error si la fecha de la tabla no tiene el formato "YYYY-MM-DD"
            JOptionPane.showMessageDialog(this, "Error en el formato de la fecha. Use YYYY-MM-DD.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // ¡Aquí capturamos NUESTRAS validaciones de negocio!
            // (Ej: "El título debe tener al menos 5 caracteres")
            JOptionPane.showMessageDialog(this, "Error de validación: " + ex.getMessage(), "Datos Incorrectos", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            // Error de la base de datos (conexión, clave duplicada, etc.)
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Captura cualquier otro error inesperado
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butGuardarCambiosActionPerformed

    private void butBuscarPorCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarPorCarteleraActionPerformed
        List<Pelicula> listaPeliculas = null;
        try {
            listaPeliculas = peliculaData.listarPeliculasEnCartelera();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las películas de la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaPeliculas.getModel();
        modelo.setRowCount(0);

        if (listaPeliculas == null) {
            JOptionPane.showMessageDialog(this,
                    "Error, no hay peliculas cargadas en la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Pelicula pelicula : listaPeliculas) {
            Object[] fila = {pelicula.getCodPelicula(), pelicula.getTitulo(), pelicula.getDirector(), pelicula.getActores(), pelicula.getOrigen(), pelicula.getGenero(), pelicula.getEstreno(), pelicula.isEnCartelera()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_butBuscarPorCarteleraActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        cargarPeliculas();
    }//GEN-LAST:event_butCancelarActionPerformed


    private void butReiniciarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReiniciarTablaActionPerformed
        cargarPeliculas();
    }//GEN-LAST:event_butReiniciarTablaActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
     
    int filaSeleccionada = TablaPeliculas.getSelectedRow();

   
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Error: Debe seleccionar una película de la tabla.", "Error al Eliminar", JOptionPane.ERROR_MESSAGE);
        return; 
    }

  
    int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar esta película?", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
          
            int idPelicula = (Integer) TablaPeliculas.getValueAt(filaSeleccionada, 0);

          
            boolean exito = peliculaData.eliminarPelicula(idPelicula);

         
            if (exito) {
                JOptionPane.showMessageDialog(this, "Película eliminada exitosamente.");
                
             
                cargarPeliculas(); 
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la película (ID no encontrado).", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
         
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        } catch (ClassCastException cce) {
           
            JOptionPane.showMessageDialog(this, "Error interno: No se pudo leer el ID de la tabla.", "Error de Tipo", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_butEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PeliculaDesktop;
    private javax.swing.JTable TablaPeliculas;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butBuscarPorCartelera;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butGuardarCambios;
    private javax.swing.JButton butNuevaPelicula;
    private javax.swing.JButton butReiniciarTabla;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtBuscarPelicula;
    // End of variables declaration//GEN-END:variables
}
