/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JInternalFrame;
import Persistencia.CompradorData;
import Persistencia.DetalleTicketData;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.PeliculaData;
import Persistencia.SalaData;
import Persistencia.TicketData;

/**
 *
 * @author FRANCO
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    private final CompradorData CompradorData;
    private final DetalleTicketData detalleTicketData;
    private final FuncionData funcionData;
    private final LugarData lugarData;
    private final PeliculaData peliculaData;
    private final SalaData salaData;
    private TicketData ticketData;
   
    public VistaPrincipal(CompradorData CompradorData, DetalleTicketData detalleTicketData, FuncionData funcionData, LugarData lugarData, PeliculaData peliculaData, SalaData salaData, TicketData ticketData) {
        initComponents();
        this.CompradorData = CompradorData;
        this.detalleTicketData = detalleTicketData;
        this.funcionData = funcionData;
        this.lugarData = lugarData;
        this.peliculaData = peliculaData;
        this.salaData = salaData;
        this.ticketData = ticketData;
    }
    
      public void abrirInternal(JInternalFrame nuevo) {
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            frame.dispose();
        }
        Escritorio.add(nuevo);
        nuevo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        CompradorMenuItem = new javax.swing.JMenuItem();
        itemTicket = new javax.swing.JMenuItem();
        itemLugar = new javax.swing.JMenuItem();
        itemFuncion = new javax.swing.JMenuItem();
        itemSala = new javax.swing.JMenuItem();
        itemPelicula = new javax.swing.JMenuItem();
        menuTaquilla = new javax.swing.JMenu();
        menuOnline = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );

        menuAdministracion.setText("Administracion");
        menuAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdministracionActionPerformed(evt);
            }
        });

        CompradorMenuItem.setText("Comprador");
        CompradorMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompradorMenuItemMouseClicked(evt);
            }
        });
        CompradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompradorMenuItemActionPerformed(evt);
            }
        });
        menuAdministracion.add(CompradorMenuItem);

        itemTicket.setText("Ticket");
        menuAdministracion.add(itemTicket);

        itemLugar.setText("Lugar");
        itemLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLugarActionPerformed(evt);
            }
        });
        menuAdministracion.add(itemLugar);

        itemFuncion.setText("Funcion");
        menuAdministracion.add(itemFuncion);

        itemSala.setText("Sala");
        itemSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalaActionPerformed(evt);
            }
        });
        menuAdministracion.add(itemSala);

        itemPelicula.setText("Pelicula");
        itemPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemPeliculaMouseClicked(evt);
            }
        });
        itemPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPeliculaActionPerformed(evt);
            }
        });
        menuAdministracion.add(itemPelicula);

        jMenuBar1.add(menuAdministracion);

        menuTaquilla.setText("Taquilla");
        jMenuBar1.add(menuTaquilla);

        menuOnline.setText("Online");
        jMenuBar1.add(menuOnline);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSalaActionPerformed

    private void CompradorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompradorMenuItemActionPerformed
        // TODO add your handling code here:
           VistaComprador vc  = new VistaComprador(CompradorData);
           abrirInternal(vc);
    }//GEN-LAST:event_CompradorMenuItemActionPerformed

    private void CompradorMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompradorMenuItemMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CompradorMenuItemMouseClicked

    private void menuAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministracionActionPerformed
      
    }//GEN-LAST:event_menuAdministracionActionPerformed

    private void itemPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPeliculaActionPerformed
       VistaPelicula vp = new VistaPelicula(peliculaData);
       abrirInternal(vp);
    }//GEN-LAST:event_itemPeliculaActionPerformed

    private void itemPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemPeliculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPeliculaMouseClicked

    private void itemLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLugarActionPerformed
         VistaLugar vl = new VistaLugar(peliculaData,funcionData,lugarData);
       abrirInternal(vl);
    }//GEN-LAST:event_itemLugarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CompradorMenuItem;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem itemFuncion;
    private javax.swing.JMenuItem itemLugar;
    private javax.swing.JMenuItem itemPelicula;
    private javax.swing.JMenuItem itemSala;
    private javax.swing.JMenuItem itemTicket;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuOnline;
    private javax.swing.JMenu menuTaquilla;
    // End of variables declaration//GEN-END:variables
}
