/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Lugar;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.PeliculaData;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCO
 */
public class VistaLugar extends javax.swing.JInternalFrame {

    private final PeliculaData peliculaData;
    private final FuncionData funcionData;
    private final LugarData lugarData;

    public VistaLugar(PeliculaData peliculaData, FuncionData funcionData, LugarData lugarData) {
        this.peliculaData = peliculaData;
        this.funcionData = funcionData;
        this.lugarData = lugarData;
        lugarData.setFuncionData(funcionData);
        initComponents();
        cargarLugares();
    }

    private void cargarLugares() {
        List<Lugar> listaLugares = null;
        try {
            listaLugares = lugarData.listarLugares();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los lugares de la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);

        if (listaLugares == null) {
            JOptionPane.showMessageDialog(this,
                    "Error, no hay lugares cargados en la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Lugar lugar : listaLugares) {
            Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        LugarDesktop = new javax.swing.JDesktopPane();
        butCancelar = new javax.swing.JButton();
        butNuevosLugares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLugares = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarLugar = new java.awt.TextField();
        butBuscar = new javax.swing.JButton();
        butGuardarCambios = new javax.swing.JButton();
        butReiniciar = new javax.swing.JButton();
        buscarPorFuncion = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        butNuevosLugares.setText("Nuevos Lugares");
        butNuevosLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevosLugaresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Lugares");

        TablaLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CodLugar", "fila", "numero", "estado", "CodFuncion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaLugares);

        jLabel2.setText("Buscar Lugar:");

        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        butGuardarCambios.setText("Guardar Cambios");
        butGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarCambiosActionPerformed(evt);
            }
        });

        butReiniciar.setText("Reiniciar Tabla");
        butReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReiniciarActionPerformed(evt);
            }
        });

        buscarPorFuncion.setText("Buscar Por Funcion");
        buscarPorFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFuncionActionPerformed(evt);
            }
        });

        LugarDesktop.setLayer(butCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butNuevosLugares, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(txtBuscarLugar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butGuardarCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(buscarPorFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LugarDesktopLayout = new javax.swing.GroupLayout(LugarDesktop);
        LugarDesktop.setLayout(LugarDesktopLayout);
        LugarDesktopLayout.setHorizontalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(butReiniciar)
                .addGap(18, 18, 18)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addComponent(butNuevosLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugarDesktopLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butBuscar)
                .addGap(18, 18, 18)
                .addComponent(buscarPorFuncion)
                .addGap(125, 125, 125))
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LugarDesktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LugarDesktopLayout.setVerticalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugarDesktopLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butBuscar)
                        .addComponent(buscarPorFuncion))
                    .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNuevosLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LugarDesktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LugarDesktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LugarDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNuevosLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevosLugaresActionPerformed

        NuevoLugar nl = new NuevoLugar(lugarData, funcionData);
        LugarDesktop.add(nl);
        nl.setVisible(true);
    }//GEN-LAST:event_butNuevosLugaresActionPerformed

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        String buscarLugar = txtBuscarLugar.getText();
        int codLugar = 0;

        if (buscarLugar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo del lugar", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            codLugar = Integer.parseInt(buscarLugar);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Lugar lugar = null;
        lugar = lugarData.buscarLugar(codLugar);

        if (lugar == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el lugar con ese id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);
        Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
        modelo.addRow(fila);
    }//GEN-LAST:event_butBuscarActionPerformed

    private void butGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarCambiosActionPerformed
        if (TablaLugares.isEditing()) {
            TablaLugares.getCellEditor().stopCellEditing();
        }

        int filaSeleccionada = TablaLugares.getSelectedRow();
        int codLugar = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 0).toString());
        //char fila = (TablaLugares.getValueAt(filaSeleccionada, 2).toString().charAt(0));
        //int numero = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 3).toString());
        boolean estado = Boolean.parseBoolean(TablaLugares.getValueAt(filaSeleccionada, 3).toString());
        //int codFuncion =Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 5).toString());
        
        
        Lugar lugar;
       
        
        
        try {
            lugarData.actualizarLugar(codLugar,estado);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error, al actualizar datos en la base de datos.", "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(null, "El lugar se modifico correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_butGuardarCambiosActionPerformed

    private void butReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReiniciarActionPerformed
        cargarLugares();
    }//GEN-LAST:event_butReiniciarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed

    }//GEN-LAST:event_butCancelarActionPerformed

    private void buscarPorFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFuncionActionPerformed
  
    if (txtBuscarLugar.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Debe ingresar un código de función.",
                "Error de validación",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int codFuncion;
    try {
        codFuncion = Integer.parseInt(txtBuscarLugar.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "El código de función debe ser un número entero válido.",
                "Error de formato",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    List<Lugar> listaLugares = null;
    
    listaLugares = lugarData.obtenerLugaresPorFuncion(codFuncion);


    DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
    modelo.setRowCount(0);

    if (listaLugares == null || listaLugares.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "No se encontraron lugares para la función con código " + codFuncion + ".",
                "Sin resultados",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }

 
    for (Lugar lugar : listaLugares) {
        Object[] fila = {
            lugar.getCodLugar(),
            lugar.getFila(),
            lugar.getNumero(),
            lugar.isEstado(),
            lugar.getFuncion().getCodFuncion()
        };
        modelo.addRow(fila);
    }
    }//GEN-LAST:event_buscarPorFuncionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane LugarDesktop;
    private javax.swing.JTable TablaLugares;
    private javax.swing.JButton buscarPorFuncion;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butGuardarCambios;
    private javax.swing.JButton butNuevosLugares;
    private javax.swing.JButton butReiniciar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtBuscarLugar;
    // End of variables declaration//GEN-END:variables
}
