/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCO
 */
public class VistaPelicula extends javax.swing.JInternalFrame {

    private PeliculaData peliculaData;
    
    public VistaPelicula(PeliculaData peliculaData) {
        initComponents();
        this.peliculaData=peliculaData;
        cargarPeliculas();
    }

    
    private void cargarPeliculas() {
          List<Pelicula> listaPeliculas =null;
        try{
            listaPeliculas = peliculaData.listarPeliculas();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, 
                              "Error al cargar las películas de la base de datos.",
                              "Error de Base de Datos",
                              JOptionPane.ERROR_MESSAGE);
        }
        

        DefaultTableModel modelo = (DefaultTableModel) TablaPeliculas.getModel();
        modelo.setRowCount(0);
        
        if(listaPeliculas==null){
            JOptionPane.showMessageDialog(this, 
                              "Error, no hay peliculas cargadas en la base de datos.",
                              "Error de Base de Datos",
                              JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Pelicula pelicula : listaPeliculas) {
            Object[] fila = {pelicula.getCodPelicula(), pelicula.getTitulo(), pelicula.getDirector(),pelicula.getActores(), pelicula.getOrigen(), pelicula.getGenero(),pelicula.getEstreno(),pelicula.isEnCartelera()};
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPeliculas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarPelicula = new java.awt.TextField();
        butBuscar = new javax.swing.JButton();
        butBuscarPorCartelera = new javax.swing.JButton();
        butGuardarCambios = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        butNuevaPelicula = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Pelicula");

        TablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CodPelicula", "titulo", "director", "actores", "origen", "genero", "estreno", "enCartelera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPeliculas);

        jLabel2.setText("Buscar Pelicula:");

        butBuscar.setText("Buscar");

        butBuscarPorCartelera.setText("Buscar Por Cartelera");

        butGuardarCambios.setText("Guardar Cambios");
        butGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarCambiosActionPerformed(evt);
            }
        });

        butCancelar.setText("Cancelar");

        butNuevaPelicula.setText("Nueva Pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butNuevaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butGuardarCambios)
                        .addGap(18, 18, 18)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butBuscar)
                        .addGap(32, 32, 32)
                        .addComponent(butBuscarPorCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtBuscarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(butBuscar)
                                    .addComponent(butBuscarPorCartelera))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butNuevaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarCambiosActionPerformed
          if (TablaPeliculas.isEditing()) {
            TablaPeliculas.getCellEditor().stopCellEditing();
        }

        int filaSeleccionada = TablaPeliculas.getSelectedRow();
        String titulo = (TablaPeliculas.getValueAt(filaSeleccionada, 1).toString());
        String director = (TablaPeliculas.getValueAt(filaSeleccionada, 2).toString());
        String actores = (TablaPeliculas.getValueAt(filaSeleccionada, 3).toString());
        String origen = (TablaPeliculas.getValueAt(filaSeleccionada, 4).toString());
        String genero = (TablaPeliculas.getValueAt(filaSeleccionada, 5).toString());
        LocalDate estreno = LocalDate.parse(TablaPeliculas.getValueAt(filaSeleccionada, 6).toString());
        boolean enCartelera = Boolean.parseBoolean(TablaPeliculas.getValueAt(filaSeleccionada, 7).toString());
        int codPelicula = Integer.parseInt(TablaPeliculas.getValueAt(filaSeleccionada, 0).toString());
        Pelicula pelicula;
        try {
            pelicula = peliculaData.buscarPelicula(codPelicula);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, 
                              "Error, al buscar la pelicula en la base de datos.",
                              "Error de Base de Datos",
                              JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        pelicula.setTitulo(titulo);
        pelicula.setDirector(director);
        pelicula.setActores(actores);
        pelicula.setOrigen(origen);
        pelicula.setGenero(genero);
        pelicula.setEstreno(estreno);
        pelicula.setEnCartelera(enCartelera);
        System.out.println(estreno);
        try {
            peliculaData.actualizarPelicula(codPelicula,"titulo",pelicula.getTitulo());
            peliculaData.actualizarPelicula(codPelicula,"director",pelicula.getDirector());
            peliculaData.actualizarPelicula(codPelicula,"actores",pelicula.getActores());
            peliculaData.actualizarPelicula(codPelicula,"origen",pelicula.getOrigen());
            peliculaData.actualizarPelicula(codPelicula,"genero",pelicula.getGenero());
            peliculaData.actualizarPelicula(codPelicula,"estreno",pelicula.getEstreno());
            peliculaData.actualizarPelicula(codPelicula,"enCartelera",pelicula.isEnCartelera());
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, 
                              "Error, al actualizar datos en la base de datos.",
                              "Error de Base de Datos",
                              JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        JOptionPane.showMessageDialog(null, "Los datos fueron actualizados correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_butGuardarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPeliculas;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butBuscarPorCartelera;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butGuardarCambios;
    private javax.swing.JButton butNuevaPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtBuscarPelicula;
    // End of variables declaration//GEN-END:variables
}
