
package Vista;

import Modelo.Lugar;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.PeliculaData;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

//para mostrar todos los asientos de todas las funcionas y hacer el crud
public class VistaLugar extends javax.swing.JInternalFrame {
    //obviamente todas las clases datas para comunicarnos con la db
    private final FuncionData funcionData;
    private final LugarData lugarData;

    public VistaLugar(PeliculaData peliculaData, FuncionData funcionData, LugarData lugarData) {
        this.funcionData = funcionData;
        this.lugarData = lugarData;
        //pasamos el funcionData al lugarData para buscar las funciones completas al listar los asientos
        lugarData.setFuncionData(funcionData);
        initComponents();

        cargarLugares();
    }
    //llena el jtable con todos los asientos de todas las funciones de la db
    private void cargarLugares() {
        List<Lugar> listaLugares = null;
        try {
            listaLugares = lugarData.listarLugares();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los lugares de la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);

        if (listaLugares == null) {
            JOptionPane.showMessageDialog(this,
                    "Error, no hay lugares cargados en la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Lugar lugar : listaLugares) {
            Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        ImageIcon icono = new ImageIcon(getClass().getResource("/Fondos/img/fondo-administracion2.jpg"));
        Image miImagen = icono.getImage();
        LugarDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0, getWidth(), getHeight(),this);
            }

        };
        butCancelar = new javax.swing.JButton();
        butNuevosLugares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarLugar = new java.awt.TextField();
        butBuscar = new javax.swing.JButton();
        butGuardarCambios = new javax.swing.JButton();
        butReiniciar = new javax.swing.JButton();
        buscarPorFuncion = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLugares = new javax.swing.JTable();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/icons8-cross-mark-48.png"))); // NOI18N
        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        butNuevosLugares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/asiento-de-cine (1).png"))); // NOI18N
        butNuevosLugares.setText("Nuevos Lugares");
        butNuevosLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevosLugaresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de Lugares");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Lugar:");

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/lupa.png"))); // NOI18N
        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        butGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Iconos/001-dos-caminos.png"))); // NOI18N
        butGuardarCambios.setText("Alta/Baja");
        butGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarCambiosActionPerformed(evt);
            }
        });

        butReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/actualizar-flecha.png"))); // NOI18N
        butReiniciar.setText("Reiniciar Tabla");
        butReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReiniciarActionPerformed(evt);
            }
        });

        buscarPorFuncion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/camara-de-cine.png"))); // NOI18N
        buscarPorFuncion.setText("Buscar Por Funcion");
        buscarPorFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFuncionActionPerformed(evt);
            }
        });

        butEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/img/basura (1).png"))); // NOI18N
        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });

        TablaLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CodLugar", "fila", "numero", "estado", "CodFuncion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaLugares);

        LugarDesktop.setLayer(butCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butNuevosLugares, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(txtBuscarLugar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butGuardarCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(buscarPorFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LugarDesktopLayout = new javax.swing.GroupLayout(LugarDesktop);
        LugarDesktop.setLayout(LugarDesktopLayout);
        LugarDesktopLayout.setHorizontalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(butBuscar)
                        .addGap(31, 31, 31)
                        .addComponent(buscarPorFuncion))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LugarDesktopLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LugarDesktopLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butGuardarCambios)))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(butReiniciar)
                .addGap(34, 34, 34)
                .addComponent(butNuevosLugares)
                .addGap(41, 41, 41)
                .addComponent(butCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        LugarDesktopLayout.setVerticalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butBuscar)
                            .addComponent(buscarPorFuncion)))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butNuevosLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(LugarDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Abre la ventana NuevosLugares para crear nuevosLugares, re redundante el chico
    private void butNuevosLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevosLugaresActionPerformed
        NuevoLugar nl = new NuevoLugar(lugarData, funcionData);
        LugarDesktop.add(nl);
        nl.setVisible(true);

    }//GEN-LAST:event_butNuevosLugaresActionPerformed

    //busca un lugar especifico por su codLugar
    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        String buscarLugar = txtBuscarLugar.getText();
        int codLugar = 0;

        if (buscarLugar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo del lugar", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            codLugar = Integer.parseInt(buscarLugar);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Lugar lugar = null;
        lugar = lugarData.buscarLugar(codLugar);

        if (lugar == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el lugar con ese id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);
        Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
        modelo.addRow(fila);
    }//GEN-LAST:event_butBuscarActionPerformed

    //para modificar elestado de los asientos en la tabla
    private void butGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarCambiosActionPerformed
        if (TablaLugares.isEditing()) {
            TablaLugares.getCellEditor().stopCellEditing();
        }

        int filaSeleccionada = TablaLugares.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para modificar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            //obtenemos el codigo de la fila y el estado
            int codLugar = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 0).toString());
            boolean estado = Boolean.parseBoolean(TablaLugares.getValueAt(filaSeleccionada, 3).toString());

            if (estado != true && estado != false) {
                JOptionPane.showMessageDialog(this, "\"El estado del asiento debe ser válido (ocupado/true o libre/false).\"", "Error de Datos", JOptionPane.ERROR_MESSAGE);
            }

            boolean exito = lugarData.actualizarLugar(codLugar, estado);

            if (exito) {
                JOptionPane.showMessageDialog(this, "¡El estado del lugar se modificó correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarLugares(); // refresca la tabla
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el estado del lugar (0 filas afectadas).",
                        "Error de Actualización",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato del ID del lugar.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butGuardarCambiosActionPerformed

    private void butReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReiniciarActionPerformed
        cargarLugares();
    }//GEN-LAST:event_butReiniciarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCancelarActionPerformed

    
    //filtra la tabla para mostrar los asienots de una funcion en especifica
    private void buscarPorFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFuncionActionPerformed

        if (txtBuscarLugar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un código de función.",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codFuncion;
        try {
            //capturamos el cod de la funcion desde el textfield
            codFuncion = Integer.parseInt(txtBuscarLugar.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El código de función debe ser un número entero válido.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<Lugar> listaLugares = null;

        listaLugares = lugarData.obtenerLugaresPorFuncion(codFuncion);

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);

        if (listaLugares == null || listaLugares.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron lugares para la función con código " + codFuncion + ".",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Lugar lugar : listaLugares) {
            Object[] fila = {
                lugar.getCodLugar(),
                lugar.getFila(),
                lugar.getNumero(),
                lugar.isEstado(),
                lugar.getFuncion().getCodFuncion()
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_buscarPorFuncionActionPerformed

    //para eliminar permanentemente de la db
    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed

        int filaSeleccionada = TablaLugares.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Error: Debe seleccionar un lugar de la tabla.", "Error al Eliminar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar este lugar?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {

                int codLugar = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 0).toString());

                boolean exito = lugarData.eliminarLugar(codLugar);

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Lugar eliminado exitosamente.");

                    cargarLugares();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el lugar (ID no encontrado).", "Error", JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassCastException cce) {

                JOptionPane.showMessageDialog(this, "Error interno: No se pudo leer el ID de la tabla.", "Error de Tipo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_butEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane LugarDesktop;
    private javax.swing.JTable TablaLugares;
    private javax.swing.JButton buscarPorFuncion;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butGuardarCambios;
    private javax.swing.JButton butNuevosLugares;
    private javax.swing.JButton butReiniciar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtBuscarLugar;
    // End of variables declaration//GEN-END:variables
}
