/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author FRANCO
 */
public class VistaTaquilla extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaTaquilla
     */
    public VistaTaquilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        labelPrecios = new javax.swing.JLabel();
        labelPeliculas = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        labelFechaFuncion = new javax.swing.JLabel();
        butNuevoComprador = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPrecio3d = new javax.swing.JTextField();
        labelPorDefecto = new javax.swing.JLabel();
        boxPeliculas = new javax.swing.JComboBox<>();
        boxFechaFuncion = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        labelHorario = new javax.swing.JLabel();
        boxTipoFunciones = new javax.swing.JComboBox<>();
        boxHorarios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        labelComprador = new javax.swing.JLabel();
        butCancelar = new javax.swing.JButton();
        labellLugaresDisponibles = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        labelTipoFuncion1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        labellLugaresDisponibles1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        labelCombo = new javax.swing.JLabel();
        labelCombo1 = new javax.swing.JLabel();
        labelCombo2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPrecio2d = new javax.swing.JTextField();
        butLugaresDisponibles = new javax.swing.JButton();
        butGenerarTicket = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        button1.setLabel("button1");

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dni");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        labelPrecios.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labelPrecios.setForeground(new java.awt.Color(255, 255, 255));
        labelPrecios.setText("Precios");
        getContentPane().add(labelPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, -1, -1));

        labelPeliculas.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        labelPeliculas.setText("Peliculas");
        getContentPane().add(labelPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        butBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\lupa.png")); // NOI18N
        butBuscar.setText("Buscar");
        getContentPane().add(butBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        labelFechaFuncion.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelFechaFuncion.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaFuncion.setText("Fecha Funcion");
        getContentPane().add(labelFechaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        butNuevoComprador.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\agregar-usuario.png")); // NOI18N
        butNuevoComprador.setText("Nuevo Comprador");
        getContentPane().add(butNuevoComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 990, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 980, 20));
        getContentPane().add(txtPrecio3d, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 100, -1));

        labelPorDefecto.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelPorDefecto.setForeground(new java.awt.Color(255, 255, 255));
        labelPorDefecto.setText("Por Defecto (No)");
        getContentPane().add(labelPorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        boxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, -1));

        boxFechaFuncion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxFechaFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 990, 20));

        labelHorario.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelHorario.setForeground(new java.awt.Color(255, 255, 255));
        labelHorario.setText("Horario");
        getContentPane().add(labelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        boxTipoFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxTipoFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 220, -1));

        boxHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 200, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Venta de Entrada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        labelComprador.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelComprador.setForeground(new java.awt.Color(255, 255, 255));
        labelComprador.setText("Comprador");
        getContentPane().add(labelComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        butCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\icons8-cross-mark-48.png")); // NOI18N
        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 130, 50));

        labellLugaresDisponibles.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labellLugaresDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        labellLugaresDisponibles.setText("Total");
        getContentPane().add(labellLugaresDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jToggleButton1.setText("Si / No");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 130, 50));

        labelTipoFuncion1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        labelTipoFuncion1.setForeground(new java.awt.Color(255, 255, 255));
        labelTipoFuncion1.setText("Tipo de Funcion");
        getContentPane().add(labelTipoFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 980, 20));

        labellLugaresDisponibles1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labellLugaresDisponibles1.setForeground(new java.awt.Color(255, 255, 255));
        labellLugaresDisponibles1.setText("Lugares Disponibles");
        getContentPane().add(labellLugaresDisponibles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 140, -1));

        labelCombo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labelCombo.setForeground(new java.awt.Color(255, 255, 255));
        labelCombo.setText("3D");
        getContentPane().add(labelCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        labelCombo1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labelCombo1.setForeground(new java.awt.Color(255, 255, 255));
        labelCombo1.setText("Combo 2x1");
        getContentPane().add(labelCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        labelCombo2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        labelCombo2.setForeground(new java.awt.Color(255, 255, 255));
        labelCombo2.setText("2D");
        getContentPane().add(labelCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 140, -1));
        getContentPane().add(txtPrecio2d, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 100, -1));

        butLugaresDisponibles.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\silla.png")); // NOI18N
        butLugaresDisponibles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        butLugaresDisponibles.setBorderPainted(false);
        butLugaresDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLugaresDisponiblesActionPerformed(evt);
            }
        });
        getContentPane().add(butLugaresDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 60, 70));

        butGenerarTicket.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\iconticket.jpg")); // NOI18N
        butGenerarTicket.setText(" Generar Ticket");
        butGenerarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGenerarTicketActionPerformed(evt);
            }
        });
        getContentPane().add(butGenerarTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 190, 50));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRANCO\\Documents\\NetBeansProjects\\CineCentro\\GP7-proyectoCinemaCentro\\img\\fondo.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 990, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butLugaresDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLugaresDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butLugaresDisponiblesActionPerformed

    private void butGenerarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGenerarTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butGenerarTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFechaFuncion;
    private javax.swing.JComboBox<String> boxHorarios;
    private javax.swing.JComboBox<String> boxPeliculas;
    private javax.swing.JComboBox<String> boxTipoFunciones;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butGenerarTicket;
    private javax.swing.JButton butLugaresDisponibles;
    private javax.swing.JButton butNuevoComprador;
    private java.awt.Button button1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelCombo;
    private javax.swing.JLabel labelCombo1;
    private javax.swing.JLabel labelCombo2;
    private javax.swing.JLabel labelComprador;
    private javax.swing.JLabel labelFechaFuncion;
    private javax.swing.JLabel labelHorario;
    private javax.swing.JLabel labelPeliculas;
    private javax.swing.JLabel labelPorDefecto;
    private javax.swing.JLabel labelPrecios;
    private javax.swing.JLabel labelTipoFuncion1;
    private javax.swing.JLabel labellLugaresDisponibles;
    private javax.swing.JLabel labellLugaresDisponibles1;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtPrecio2d;
    private javax.swing.JTextField txtPrecio3d;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
