/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Lugar;
import Persistencia.FuncionData;
import Persistencia.LugarData;
import Persistencia.PeliculaData;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANCO
 */
public class VistaLugar extends javax.swing.JInternalFrame {

    private final FuncionData funcionData;
    private final LugarData lugarData;

    public VistaLugar(PeliculaData peliculaData, FuncionData funcionData, LugarData lugarData) {
        this.funcionData = funcionData;
        this.lugarData = lugarData;
        lugarData.setFuncionData(funcionData);
        initComponents();
        cargarLugares();
    }

    private void cargarLugares() {
        List<Lugar> listaLugares = null;
        try {
            listaLugares = lugarData.listarLugares();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los lugares de la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);

        if (listaLugares == null) {
            JOptionPane.showMessageDialog(this,
                    "Error, no hay lugares cargados en la base de datos.",
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Lugar lugar : listaLugares) {
            Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        LugarDesktop = new javax.swing.JDesktopPane();
        butCancelar = new javax.swing.JButton();
        butNuevosLugares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLugares = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarLugar = new java.awt.TextField();
        butBuscar = new javax.swing.JButton();
        butGuardarCambios = new javax.swing.JButton();
        butReiniciar = new javax.swing.JButton();
        buscarPorFuncion = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        butNuevosLugares.setText("Nuevos Lugares");
        butNuevosLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevosLugaresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Lugares");

        TablaLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CodLugar", "fila", "numero", "estado", "CodFuncion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaLugares);

        jLabel2.setText("Buscar Lugar:");

        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        butGuardarCambios.setText("Guardar Cambios");
        butGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarCambiosActionPerformed(evt);
            }
        });

        butReiniciar.setText("Reiniciar Tabla");
        butReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReiniciarActionPerformed(evt);
            }
        });

        buscarPorFuncion.setText("Buscar Por Funcion");
        buscarPorFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFuncionActionPerformed(evt);
            }
        });

        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });

        LugarDesktop.setLayer(butCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butNuevosLugares, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(txtBuscarLugar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butGuardarCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(buscarPorFuncion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LugarDesktop.setLayer(butEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LugarDesktopLayout = new javax.swing.GroupLayout(LugarDesktop);
        LugarDesktop.setLayout(LugarDesktopLayout);
        LugarDesktopLayout.setHorizontalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(buscarPorFuncion))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LugarDesktopLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(butReiniciar)
                        .addGap(12, 12, 12)
                        .addComponent(butNuevosLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        LugarDesktopLayout.setVerticalGroup(
            LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugarDesktopLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(butBuscar))
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(buscarPorFuncion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugarDesktopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LugarDesktopLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(LugarDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNuevosLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(LugarDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNuevosLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevosLugaresActionPerformed

        NuevoLugar nl = new NuevoLugar(lugarData, funcionData);
        LugarDesktop.add(nl);
        nl.setVisible(true);
    }//GEN-LAST:event_butNuevosLugaresActionPerformed

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
        String buscarLugar = txtBuscarLugar.getText();
        int codLugar = 0;

        if (buscarLugar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo del lugar", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            codLugar = Integer.parseInt(buscarLugar);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Lugar lugar = null;
        lugar = lugarData.buscarLugar(codLugar);

        if (lugar == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el lugar con ese id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);
        Object[] fila = {lugar.getCodLugar(), lugar.getFila(), lugar.getNumero(), lugar.isEstado(), lugar.getFuncion().getCodFuncion()};
        modelo.addRow(fila);
    }//GEN-LAST:event_butBuscarActionPerformed

    private void butGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarCambiosActionPerformed
        if (TablaLugares.isEditing()) {
            TablaLugares.getCellEditor().stopCellEditing();
        }

        int filaSeleccionada = TablaLugares.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para modificar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            int codLugar = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 0).toString());
            boolean estado = Boolean.parseBoolean(TablaLugares.getValueAt(filaSeleccionada, 3).toString());

            if (estado != true && estado != false) {
                JOptionPane.showMessageDialog(this, "\"El estado del asiento debe ser válido (ocupado/true o libre/false).\"", "Error de Datos", JOptionPane.ERROR_MESSAGE);
            }

            boolean exito = lugarData.actualizarLugar(codLugar, estado);

            if (exito) {
                JOptionPane.showMessageDialog(this, "¡El estado del lugar se modificó correctamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarLugares(); // refresca la tabla
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el estado del lugar (0 filas afectadas).",
                        "Error de Actualización",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato del ID del lugar.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butGuardarCambiosActionPerformed

    private void butReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReiniciarActionPerformed
        cargarLugares();
    }//GEN-LAST:event_butReiniciarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed

    }//GEN-LAST:event_butCancelarActionPerformed

    private void buscarPorFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFuncionActionPerformed

        if (txtBuscarLugar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un código de función.",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codFuncion;
        try {
            codFuncion = Integer.parseInt(txtBuscarLugar.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El código de función debe ser un número entero válido.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<Lugar> listaLugares = null;

        listaLugares = lugarData.obtenerLugaresPorFuncion(codFuncion);

        DefaultTableModel modelo = (DefaultTableModel) TablaLugares.getModel();
        modelo.setRowCount(0);

        if (listaLugares == null || listaLugares.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron lugares para la función con código " + codFuncion + ".",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Lugar lugar : listaLugares) {
            Object[] fila = {
                lugar.getCodLugar(),
                lugar.getFila(),
                lugar.getNumero(),
                lugar.isEstado(),
                lugar.getFuncion().getCodFuncion()
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_buscarPorFuncionActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed

        int filaSeleccionada = TablaLugares.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Error: Debe seleccionar un lugar de la tabla.", "Error al Eliminar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar este lugar?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {

                int idPelicula = Integer.parseInt(TablaLugares.getValueAt(filaSeleccionada, 0).toString());

                boolean exito = lugarData.eliminarLugar(idPelicula);

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Lugar eliminado exitosamente.");

                    cargarLugares();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el lugar (ID no encontrado).", "Error", JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassCastException cce) {

                JOptionPane.showMessageDialog(this, "Error interno: No se pudo leer el ID de la tabla.", "Error de Tipo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_butEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane LugarDesktop;
    private javax.swing.JTable TablaLugares;
    private javax.swing.JButton buscarPorFuncion;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butGuardarCambios;
    private javax.swing.JButton butNuevosLugares;
    private javax.swing.JButton butReiniciar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextField txtBuscarLugar;
    // End of variables declaration//GEN-END:variables
}
