/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Comprador;
import Modelo.TicketCompra;
import Persistencia.CompradorData;
import Persistencia.TicketData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emiliano
 */
public class VistaTicket extends javax.swing.JInternalFrame {
    private TicketData ticketdata;
    private CompradorData compradordata;
    private DefaultTableModel modelo;
    
    
    /**
     * Creates new form VistaTicket
     */
    public VistaTicket() {
        initComponents();
        
        this.ticketdata = new TicketData();
        this.compradordata = new CompradorData();
        this.modelo = new DefaultTableModel();
        
        cargarCompradores();
        cargarTicket();
        
      
    }
    
    public void cargarCompradores(){
        try { List<Comprador> compradores = compradordata.listarCompradores();
        for (Comprador c : compradores){
            CboxComprador.addItem(c);   
        }
          } catch(Exception e){
          JOptionPane.showMessageDialog(this,"Error al cargar compradores: " + e.getMessage());
          
          }
     }
        private void cargarTicket(){
         List<TicketCompra> tickets = ticketdata.listarTickets();
        for ( TicketCompra t: tickets){
        modelo.addRow(new Object[]{
        t.getComprador().getNombre(),
        //t.getDetalleTicket().getFuncion(),
        t.getFechaCompra(),
        t.getMonto()});
        }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ButNuevo = new javax.swing.JButton();
        ButActualizar = new javax.swing.JButton();
        ButBorrar = new javax.swing.JButton();
        ButLogica = new javax.swing.JButton();
        ButMostrar = new javax.swing.JButton();
        ButBuscar = new javax.swing.JButton();
        CboxComprador = new javax.swing.JComboBox();

        setTitle("Vista Ticket");

        jDesktopPane1.setForeground(new java.awt.Color(51, 51, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gestion de Ticket");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 0, 214, -1));

        jTableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Comprador", "Funcion", "Fecha de Comprar", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTicket);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 578, 195));

        jLabel2.setText("Comprador:");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 100, -1, 31));

        ButNuevo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButNuevo.setForeground(new java.awt.Color(51, 51, 51));
        ButNuevo.setText("Nuevo");
        ButNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButNuevoActionPerformed(evt);
            }
        });
        jDesktopPane1.add(ButNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, -1, -1));

        ButActualizar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButActualizar.setForeground(new java.awt.Color(51, 51, 51));
        ButActualizar.setText("Actualizar");
        ButActualizar.setBorderPainted(false);
        jDesktopPane1.add(ButActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 391, -1, -1));

        ButBorrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButBorrar.setForeground(new java.awt.Color(51, 51, 51));
        ButBorrar.setText("Borrar");
        jDesktopPane1.add(ButBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 391, -1, -1));

        ButLogica.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButLogica.setForeground(new java.awt.Color(51, 51, 51));
        ButLogica.setText("Alta/Baja logica");
        jDesktopPane1.add(ButLogica, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 391, -1, -1));

        ButMostrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButMostrar.setForeground(new java.awt.Color(51, 51, 51));
        ButMostrar.setText("Mostrar Todos");
        jDesktopPane1.add(ButMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 391, -1, -1));

        ButBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButBuscar.setText("Buscar");
        ButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBuscarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(ButBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 100, -1, -1));

        CboxComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxCompradorActionPerformed(evt);
            }
        });
        jDesktopPane1.add(CboxComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 104, 126, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButNuevoActionPerformed
        // TODO add your handling code here:
        NuevoTicket nt = new NuevoTicket();
        getParent().add(nt);
        nt.setVisible(true);
        nt.toFront();
    }//GEN-LAST:event_ButNuevoActionPerformed

    private void CboxCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxCompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxCompradorActionPerformed

    private void ButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButActualizar;
    private javax.swing.JButton ButBorrar;
    private javax.swing.JButton ButBuscar;
    private javax.swing.JButton ButLogica;
    private javax.swing.JButton ButMostrar;
    private javax.swing.JButton ButNuevo;
    private javax.swing.JComboBox CboxComprador;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTicket;
    // End of variables declaration//GEN-END:variables
}
