/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Comprador;
import Modelo.TicketCompra;
import Persistencia.CompradorData;
import Persistencia.TicketData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emiliano
 */
public class VistaTicket extends javax.swing.JInternalFrame {
    private TicketData ticketdata;
    private CompradorData compradordata;
    private DefaultTableModel modelo;
    
    
    /**
     * Creates new form VistaTicket
     */
    public VistaTicket() {
        initComponents();
        
        this.ticketdata = new TicketData();
       this.compradordata = new CompradorData();
        this.modelo = new DefaultTableModel();
        
        cargarCompradores();
        cargarTicket();
        
      
    }
    
    public void cargarCompradores(){
        try { List<Comprador> compradores = compradordata.listarCompradores();
        for (Comprador c : compradores){
            CboxComprador.addItem(c);   
        }
          } catch(Exception e){
          JOptionPane.showMessageDialog(this,"Error al cargar compradores: " + e.getMessage());
          
          }
     }
        private void cargarTicket(){
         List<TicketCompra> tickets = ticketdata.listarTickets();
        for ( TicketCompra t: tickets){
        modelo.addRow(new Object[]{
        t.getComprador().getNombre(),
        //t.getDetalleTicket().getFuncion(),
        t.getFechaCompra(),
        t.getMonto()});
        }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ButNuevo = new javax.swing.JButton();
        ButActualizar = new javax.swing.JButton();
        ButBorrar = new javax.swing.JButton();
        ButLogica = new javax.swing.JButton();
        ButMostrar = new javax.swing.JButton();
        ButBuscar = new javax.swing.JButton();
        CboxComprador = new javax.swing.JComboBox();

        setTitle("Vista Ticket");

        jDesktopPane1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Gestion de Ticket");

        jTableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Comprador", "Funcion", "Fecha de Comprar", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTicket);

        jLabel2.setText("Comprado:");

        ButNuevo.setBackground(new java.awt.Color(255, 255, 255));
        ButNuevo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButNuevo.setForeground(new java.awt.Color(51, 51, 51));
        ButNuevo.setText("Nuevo");
        ButNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButNuevoActionPerformed(evt);
            }
        });

        ButActualizar.setBackground(new java.awt.Color(255, 255, 255));
        ButActualizar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButActualizar.setForeground(new java.awt.Color(51, 51, 51));
        ButActualizar.setText("Actualizar");
        ButActualizar.setBorderPainted(false);

        ButBorrar.setBackground(new java.awt.Color(255, 255, 255));
        ButBorrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButBorrar.setForeground(new java.awt.Color(51, 51, 51));
        ButBorrar.setText("Borrar");

        ButLogica.setBackground(new java.awt.Color(255, 255, 255));
        ButLogica.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButLogica.setForeground(new java.awt.Color(51, 51, 51));
        ButLogica.setText("Alta/Baja logica");

        ButMostrar.setBackground(new java.awt.Color(255, 255, 255));
        ButMostrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButMostrar.setForeground(new java.awt.Color(51, 51, 51));
        ButMostrar.setText("Mostrar Todos");

        ButBuscar.setBackground(new java.awt.Color(255, 255, 255));
        ButBuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ButBuscar.setForeground(new java.awt.Color(0, 0, 0));
        ButBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/imagenes/lupa.png"))); // NOI18N
        ButBuscar.setText("Buscar");

        CboxComprador.setBackground(new java.awt.Color(255, 255, 255));
        CboxComprador.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CboxComprador.setForeground(new java.awt.Color(0, 0, 0));

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButBorrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButLogica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButMostrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ButBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CboxComprador, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CboxComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButLogica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButMostrar)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButBuscar)
                    .addComponent(CboxComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButNuevo)
                    .addComponent(ButActualizar)
                    .addComponent(ButBorrar)
                    .addComponent(ButLogica)
                    .addComponent(ButMostrar))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButNuevoActionPerformed
        // TODO add your handling code here:
        NuevoTicket nt = new NuevoTicket();
        getParent().add(nt);
        nt.setVisible(true);
        nt.toFront();
    }//GEN-LAST:event_ButNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButActualizar;
    private javax.swing.JButton ButBorrar;
    private javax.swing.JButton ButBuscar;
    private javax.swing.JButton ButLogica;
    private javax.swing.JButton ButMostrar;
    private javax.swing.JButton ButNuevo;
    private javax.swing.JComboBox CboxComprador;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTicket;
    // End of variables declaration//GEN-END:variables
}
